create table "public"."test-local-bd" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test-local-bd" enable row level security;

CREATE UNIQUE INDEX "test-local-bd_pkey" ON public."test-local-bd" USING btree (id);

alter table "public"."test-local-bd" add constraint "test-local-bd_pkey" PRIMARY KEY using index "test-local-bd_pkey";

grant delete on table "public"."test-local-bd" to "anon";

grant insert on table "public"."test-local-bd" to "anon";

grant references on table "public"."test-local-bd" to "anon";

grant select on table "public"."test-local-bd" to "anon";

grant trigger on table "public"."test-local-bd" to "anon";

grant truncate on table "public"."test-local-bd" to "anon";

grant update on table "public"."test-local-bd" to "anon";

grant delete on table "public"."test-local-bd" to "authenticated";

grant insert on table "public"."test-local-bd" to "authenticated";

grant references on table "public"."test-local-bd" to "authenticated";

grant select on table "public"."test-local-bd" to "authenticated";

grant trigger on table "public"."test-local-bd" to "authenticated";

grant truncate on table "public"."test-local-bd" to "authenticated";

grant update on table "public"."test-local-bd" to "authenticated";

grant delete on table "public"."test-local-bd" to "service_role";

grant insert on table "public"."test-local-bd" to "service_role";

grant references on table "public"."test-local-bd" to "service_role";

grant select on table "public"."test-local-bd" to "service_role";

grant trigger on table "public"."test-local-bd" to "service_role";

grant truncate on table "public"."test-local-bd" to "service_role";

grant update on table "public"."test-local-bd" to "service_role";


